### ISSUE TITLE
License or privilege error

### ISSUE THREAD

**Issue by ShiriVL** [miyako/4d-plugin-xslt-v2#1]
Hello,
I tried to use this plugin on our 4D v17.
When installing on a local mac, I get a "License or privilege error" when attempting to run XSLT Apply stylesheet. When I installed it on our Mac server, and attempted to open a windows 32bit client, the windows client immediately crashed.
Any idea how to fix these issues? Is the plugin compatible with all 4D v17 versions?

**Comment by miyako** [comment]
did you use the dmg from the releases tab?

https://github.com/miyako/4d-plugin-xslt-v2/releases/tag/2.2

**Comment by ShiriVL** [comment]
Yes, at least for my testing on the local mac.

**Comment by miyako** [comment]
OK, I need to look into it.

**Comment by miyako** [comment]
I cleaned up the code to not use handles (could crash on windows, v17).
it seems ok with 17r6 Mac  and Windows.
notice there is not 32-bit version of the plugin for Mac.

v.2.3

notarisation is taking time, I will repost here when it is done

**Comment by ShiriVL** [comment]
Thank you very much!

**Comment by miyako** [comment]
https://github.com/miyako/4d-plugin-xslt-v2/releases/tag/2.3

**Comment by ShiriVL** [comment]
@miyako thank you for the speedy answer.
Unfortunately, the windows client is still crashing.

Here are more details about the crash (not sure if they are helpful or not):

Problem signature:
  Problem Event Name:	BEX
  Application Name:	4D.exe
  Application Version:	17.0.0.0
  Application Timestamp:	5bf4bbd2
  Fault Module Name:	StackHash_0a9e
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	00000000
  Exception Offset:	00000000
  Exception Code:	c0000005
  Exception Data:	00000008
  OS Version:	6.1.7601.2.1.0.16.7
  Locale ID:	1053
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by miyako** [comment]
"windows client" - do you mean, it doesn't crash single user?
I ask because the sample DB does not crash when I run it.

<img width="905" alt="スクリーンショット 2019-11-18 21 48 44" src="https://user-images.githubusercontent.com/1725068/69053666-41bebc00-0a4d-11ea-9be2-b2116a9a311a.png">

**Comment by miyako** [comment]
also, the "details" above do not help at all.
what will help is a minimal structure file that reproduces the issue.

**Comment by ShiriVL** [comment]
I may have been unclear, apologies. The windows client crashes when I open it, the code hasn't even run yet. The presence of the plugin on the server is enough to cause the windows client to crash (doesn't happen with the mac client).
Ok, thank you, I will try to run a small structure file.

**Comment by miyako** [comment]
in that case, can you list all plugins you have installed?
there could be a conflict of libxml2 init code.

**Comment by ShiriVL** [comment]
<img width="266" alt="plugins" src="https://user-images.githubusercontent.com/57701426/69056782-f1c20400-0a10-11ea-878c-ce1e0549119a.png">

I'm in the process of creating a small structure file with just the one plugin.

**Comment by miyako** [comment]
also missing in this discussion is whether the crash is specific to 32-bit.
I only tested 64-bit.

**Comment by ShiriVL** [comment]
Yes, the crash is specific to the 32bit client. Our application isn't compatible with 64bit clients yet so other things don't work if I run the 64bit one.
Is this plugin incompatible with 32bit clients then?

**Comment by ShiriVL** [comment]
I have just performed some more tests. As you said - it works just fine in 64bit (standalone on windows, minimal structure file), crashes on 32bit.

**Comment by miyako** [comment]
please try 2.4

**Comment by ShiriVL** [comment]
2.4 is working, thank you very much!
