### ISSUE TITLE
Missing .dll

### ISSUE THREAD

**Issue by ShiriVL** [miyako/4d-plugin-xslt-v2#2]
Hello again,

When installing the plugin on some of our customer's system, we found multiple occasions in which we get an error regarding a missing .dll files.
This error occurs only when opening the (32bit) client, it doesn't happen when starting the server (discovered so far on Windows server 2008 and Vista 6.3)

Is this .dll required for the plugin to work? We have it on our own test system (and it works perfectly here), but at least two of our customers' servers do not include it.
If it is required, is it possible to bundle it with the plugin?

![image](https://user-images.githubusercontent.com/57701426/69610064-568de780-102b-11ea-832c-6614643fe67f.png)

**Comment by miyako** [comment]
``vcruntime`` is a redistributable dll, 140 corresponds to visual studio 2015, I think.
you can install it manually using the official install from Microsoft. You can also put a copy inside Windows/Window64 inside the plugin.

**Comment by miyako** [comment]
a copy may or may not be present inside the system32 folder, it depends on what other app was previously installed on that pc.

**Comment by miyako** [comment]
please try 2.5

**Comment by ShiriVL** [comment]
Will do so asap, thank you! I'll post here afterwards.

**Comment by ShiriVL** [comment]
I've just tested it on a customer test server that exhibited the problem and it seems to work just fine with 2.5. Thank you kindly!
