### ISSUE TITLE
Crash when no result

### ISSUE THREAD

**Issue by rsagner** [miyako/4d-plugin-xslt-v2#5]
Hi,

On Windows 4D crashes when the resulting output is empty when using blob for input/output. In our case we have an xml with a list of persons and only if the person has a specified email address we include the data of that person into the result. We found that if the xml contains to person with email addresses it crashes.

I notice that one of your last commits says "always return something", could that be a fix for this issue? Please note we still would like an empty blob in return if the result is really empty.

Thanks, Rikard - Metodika

**Comment by miyako** [comment]
> could that be a fix for this issue? 

if you are not already using that version, yes that could be it.

**Comment by rsagner** [comment]
@miyako thanks! I can confirm release 2.6.2 fixes the issue.
