### ISSUE TITLE
Result is 0 oktets if element value exceeds 1493 rows

### ISSUE THREAD

**Issue by metodikamikaelnilsson** [miyako/4d-plugin-xslt-v2#6]
If the value of any element in the XML sent as argument to the XSLT Apply stylesheet method exceeds 1493 rows, the result is 0 oktets. N.B. it is only the _number of rows_ that seems significant, not how many characters each row is comprised of, or which characters that are included.

Is this a bug or is this limit intentional? Is there a way to increase the allowed number of rows, e.g. by adding a value to the $params argument?

**Comment by miyako** [comment]
I did not implement any such limits. I have no idea why there is a limit.
